# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo '$(Release.ReleaseId)'
- script: exit
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github_oseduardo'
    repositoryName: 'oseduardo/DVWA-master'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Release.ReleaseId)'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github_oseduardo'
    userRepository: 'oseduardo/DVWA-master'
    defaultVersionType: 'specificTag'
    version: '$(Release.ReleaseId)'
    downloadPath: '$(System.ArtifactsDirectory)'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github_oseduardo'
    userRepository: 'oseduardo/DVWA-master'
    defaultVersionType: 'latest'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.ArtifactsDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode'
    veracodeAppProfile: 'DVWA-Azure'
    version: '$(build.buildNumber)'
    filepath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    createSandBox: false
    createProfile: false
    failTheBuildIfVeracodeScanDidNotInitiate: true
    scanStatusCheckInterval: '60'
    importResults: false
    failBuildOnPolicyFail: true