# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github_oseduardo'
    repositoryName: 'oseduardo/DVWA-master'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '$(Build.BuildId)'
    assets: '$(Build.ArtifactStagingDirectory)/*'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
- task: CmdLine@2
  inputs:
    script: |
      echo Downloding artifacts fro GitHub... 
      curl -o latestrelease.zip https://github.com/oseduardo/DVWA-master/archive/'$(Build.BuildId)'.zip
      ls -l --block-size=M *
#- task: Veracode@3
#  inputs:
#    ConnectionDetailsSelection: 'Endpoint'
#    AnalysisService: 'Veracode'
#    veracodeAppProfile: 'DVWA-Azure'
#    version: '$(build.buildNumber)'
#    filepath: '$(System.ArtifactsDirectory)/latestrelease.zip'
#    createSandBox: false
#    createProfile: false
#    failTheBuildIfVeracodeScanDidNotInitiate: true
#    scanStatusCheckInterval: '60'
#    importResults: false
#    failBuildOnPolicyFail: true